### ISSUE TITLE
ipsframework not found

### ISSUE THREAD

**Issue by cianciosa** [HPC-SimTools/IPS-framework#123]
I'm trying to run my workflow on NERSC and it keeps giving my problems. 

https://github.com/ORNL-Fusion/ips-wrappers/tree/master/ips-ml-train/Test

I had to hard code the full path to make sure it's using the right version of python because it kept picking up the wrong ips install and failing since I changed the workflow to use the python modules.

```
Traceback (most recent call last):
  File "/global/homes/m/user/.local/cori/3.8-anaconda-2020.11/bin/ips.py", line 33, in <module>
    sys.exit(load_entry_point('ipsframework==0.3.0', 'console_scripts', 'ips.py')())
  File "/global/homes/m/user/.local/cori/3.8-anaconda-2020.11/bin/ips.py", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/importlib/metadata.py", line 504, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/importlib/metadata.py", line 177, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: ipsframework
```

**Comment by rosswhitfield** [comment]
Looking at [submitjob](https://github.com/ORNL-Fusion/ips-wrappers/blob/916e3b4ac1e9fcbb1d85abefd44afee28d0a5d39/ips-ml-train/Test/submitjob), I see a few potential problems.

You are adding a different IPS to your `PYTHONPATH` ([here](https://github.com/ORNL-Fusion/ips-wrappers/blob/916e3b4ac1e9fcbb1d85abefd44afee28d0a5d39/ips-ml-train/Test/submitjob#L49)) and `PATH` ([here](https://github.com/ORNL-Fusion/ips-wrappers/blob/916e3b4ac1e9fcbb1d85abefd44afee28d0a5d39/ips-ml-train/Test/submitjob#L42)) and that is probably what it is finding.

The other issue is that `module load tensorflow/intel-2.4.1` changes the python that you are using, overriding what was loaded when you did `source activate ml_train_env`. Running `ips.py` directly will use the python from your conda environment but I think then it won't actually be making use of the TensorFlow that you loaded with the module load.

One solution to try is to create an environment based on ` tensorflow/intel-2.4.1` and install your other dependencies into that. You can do

```bash
module load tensorflow/intel-2.4.1
conda create -n ml_train_env --clone root
source activate ml_train_env
python -m pip install ipsframework
...
```

Then in `submitjob` have

```bash
module load tensorflow/intel-2.4.1
source activate ml_train_env
```

where it should use the same python and tensorflow as ` tensorflow/intel-2.4.1`  and the correct IPS.

**Comment by cianciosa** [comment]
I forgot, that the tensorflow modules replaced the python module. 

Would it be possible check if multiple ipsframeworks instances are in the PYTHONPATH and emit an error message to this effect?

**Comment by cianciosa** [comment]
Thinking about this some more, this is going to be tricky. They way the entire workflow works is the ml_train launches the massive_serial_runner as a subworkflow. Then the massive_serial_runner workflow launches am ips framework instance as a task. The install of ips-fastran has not been updated for the new ips-framework install. So I probably need to create a conda environment for just fastran.

So the question is there away to setup a python environment from inside an IPS component and would that cause interference with the parent IPS instance?

**Comment by elwasif** [comment]
> Then the massive_serial_runner workflow launches am ips framework instance as a task. The install of ips-fastran has not been updated for the new ips-framework install. So I probably need to create a conda environment for just fastran.

I think the ips-fastran has been ported to the new structure of the ipsframework (maybe in a branch). The other route would be to keep using the "old" ips in tasks launched from the massive_serial_runner, by having a simple wrapper script like
```bash
#!/bin/bash
module load python  #this will load Cori's default python environment
#Setup PYTHONPATH  and other environment vars for ips-fastran
/path/to/old/ips.py $*
```
I "think" this should work, but the interaction between the different Python environment might cause issue.

**Comment by cianciosa** [comment]
I'm already running into problem with PYTHONPATH when trying to setup a virtual environment. I would had thought that setting up a virtual env would have created a completely isolated system but it just references the system PYTHONPATH anyways. I'm kind of stumped on away to make these environments sandboxed.

**Comment by elwasif** [comment]
I think there are flags when you create a virtual environment / conda that would allow you to ing=herit systempackages or not, so maybe that's worthy of exploration

**Comment by cianciosa** [comment]
It looks like `conda env config vars set var=value` did the trick. That will work from the parent environment. So I'll test to see if I can activate a conda environment from inside a conda environment.

**Comment by cianciosa** [comment]
It looks like it sort of works

```
(base) $:~> conda activate ml_train_env
WARNING: overwriting environment variables set in the machine
overwriting variable PYTHONPATH
(ml_train_env) $:~> conda activate subenv
WARNING: overwriting environment variables set in the machine
overwriting variable PYTHONPATH
(subenv) $:~> which ips.py
which: no ips.py in (/global/homes/m/user/.conda/envs/subenv/bin:/usr/common/software/tensorflow/intel-tensorflow/2.4.1/condabin:/opt/cray/pe/netcdf/4.6.1.3/bin:/global/common/sw/cray/cnl7/haswell/cmake/3.14.4/gcc/8.2.0/2hef55n/bin:/opt/cray/pe/mpt/7.7.10/gni/bin:/opt/cray/rca/2.2.20-7.0.1.1_4.62__g8e3fb5b.ari/bin:/opt/cray/alps/6.6.58-7.0.1.1_6.20__g437d88db.ari/sbin:/opt/cray/alps/default/bin:/opt/cray/job/2.2.4-7.0.1.1_3.48__g36b56f4.ari/bin:/opt/cray/pe/craype/2.6.2/bin:/opt/intel/compilers_and_libraries_2019.3.199/linux/bin/intel64:/usr/common/software/darshan/3.2.1/bin:/global/common/cori/software/altd/2.0/bin:/usr/common/software/bin:/usr/common/nsg/bin:/opt/ovis/bin:/opt/ovis/sbin:/opt/cray/pe/modules/3.2.11.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/opt/cray/pe/bin)
(subenv) $:~> conda deactivate
(ml_train_env) $:~> which ips.py
/global/homes/m/user/.conda/envs/ml_train_env/bin/ips.py
(ml_train_env) $:~> 
```

I guess using this I could make a script 
```
conda activate subenv
old/ips.py --simulation=massive_serial --platform....
conda deactivate subenv
```
That launch_task can run. This should restore everything back to normal so probably won't interfere with the parent ipsframework.

**Comment by elwasif** [comment]
So It looks like your using the default conda settings which is putting all environments in $HOME/.conda/envs. I think conda can be configured to use a different directory, and I wonder if using a directory on the lustre project space would improve performance.
