### ISSUE TITLE
Migrate existing IPS ATOM Tasks to new github project standard.

### ISSUE THREAD

**Issue by markcoletti** [HPC-SimTools/IPS-framework#187]
The "classic project" fomat is sunsetting on August 23rd. 
 Oops.  That's passed.  In any case, there's a "start migration" button that allegedly will do this for us. 

See also: https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/

**Comment by elwasif** [comment]
Migrated to new Project using GitHub migration button.
