### ISSUE TITLE
Implement container-based massive serial execution capability

### ISSUE THREAD

**Issue by bernhold** [HPC-SimTools/IPS-framework#30]

**Comment by elwasif** [comment]
Implemented  : See

@INPROCEEDINGS {9297046,
author = {W. Elwasif and R. Whitfield and J. Park and M. Cianciosa},
booktitle = {2020 2nd International Workshop on Containers and New Orchestration Paradigms for Isolated Environments in HPC (CANOPIE-HPC)},
title = {Containers for Massive Ensemble of I/O Bound Hierarchical Coupled Simulations},
year = {2020},
volume = {},
issn = {},
pages = {26-34},
keywords = {ip networks;task analysis;data models;computational modeling;biological system modeling;resource management;containers},
doi = {10.1109/CANOPIEHPC51917.2020.00009},
url = {https://doi.ieeecomputersociety.org/10.1109/CANOPIEHPC51917.2020.00009},
publisher = {IEEE Computer Society},
address = {Los Alamitos, CA, USA},
month = {nov}
}
