### ISSUE TITLE
Staging separate state files

### ISSUE THREAD

**Issue by rosmirnov** [HPC-SimTools/IPS-framework#40]
This is a suggestion on adding a feature to IPS. Currently, there is possibility to update specific state files using

services.update_state([state_file])

However, staging state can be done only as a whole

services.stage_state()

It would be useful to have ability to stage separate files as well, e.g.

services.stage_state([state_file])

For example, when one tries to obtain grid dimensions nx, ny from 'init' method of component2D via a state file, another state file (containing array of size ny and used by 'init' of component1D) does not exist yet and services.stage_state() fails.

**Comment by elwasif** [comment]
Enhancement applied.
