### ISSUE TITLE
When using multiple configuration files the work directory isn't initialize correctly

### ISSUE THREAD

**Issue by rosswhitfield** [HPC-SimTools/IPS-framework#59]
If you do something like `ips.py -config=sim1.cfg,sim2.cfg ...` the working directory is created for each config according to their `SIM_ROOT` but input files for both configurations are always copied to the first working directory only.

This test shows the bug, as these lines should be able to be removed https://github.com/HPC-SimTools/IPS-framework/blob/119dafa49b55e4a2b31f1e10a674333aff172d0f/tests/multirun/test_basic_serial.py#L137-L139

**Comment by elwasif** [comment]
@rosswhitfield  should this issue be closed now?
