### ISSUE TITLE
Fine grain sub workflow output staging

### ISSUE THREAD

**Issue by cianciosa** [HPC-SimTools/IPS-framework#6]
The current implementation of `update_plasma_state` assumes all subflows have already run. If a sub workflow has not run yet, an exception is throw because the expected output file does not exist.

**Comment by elwasif** [comment]
I've updated `stage_subflow_output_files()` to take an optional argument sim_name to specify which subflow to target (default value is string "ALL"). it also now return a dictionary of all subflows that have been processed and the corresponding output files that have been staged (see commit 0679868ae06ac8e3f8f39c7f60d7849526629053 ). This change is in the wael_dev branch (for testing)

**Comment by elwasif** [comment]
Feature available now on master branch
